export enum EstadoCobroEnum {
  PENDIENTE = 'PENDIENTE',
  PAGADO = 'PAGADO',
  VENCIDO = 'VENCIDO',
  ANULADO = 'ANULADO',
  EN_PRORROGA = 'EN_PRORROGA',
  PAGADO_PARCIALMENTE = 'PAGADO_PARCIALMENTE',
}
