export enum EstadoPagoLoteoEnum {
  AL_DIA = 'AL_DIA',
  EN_PERIODO_DE_GRACIA = 'EN_PERIODO_DE_GRACIA',
  SUSPENDIDO_POR_FALTA_PAGO = 'SUSPENDIDO_POR_FALTA_PAGO',
  DE_BAJA_POR_FALTA_PAGO = 'DE_BAJA_POR_FALTA_PAGO',
  PLAN_DE_PRUEBA = 'PLAN_DE_PRUEBA',
  PLAN_GRATUITO_ESPECIAL = 'PLAN_GRATUITO_ESPECIAL',
}
