export enum EstadoCuentaPlataformaEnum {
  PENDIENTE_ACTIVACION_EMAIL = 'PENDIENTE_ACTIVACION_EMAIL',
  PENDIENTE_CAMBIO_CLAVE_TEMPORAL = 'PENDIENTE_CAMBIO_CLAVE_TEMPORAL',
  ACTIVO = 'ACTIVO',
  SUSPENDIDO_POR_ADMIN_PLATAFORMA = 'SUSPENDIDO_POR_ADMIN_PLATAFORMA',
  SUSPENDIDO_POR_ADMIN_LOTEO = 'SUSPENDIDO_POR_ADMIN_LOTEO',
  BLOQUEADO_INTENTOS_FALLIDOS = 'BLOQUEADO_INTENTOS_FALLIDOS',
  INACTIVO_POR_BAJA = 'INACTIVO_POR_BAJA',
}
