export enum EstadoParcelaEnum {
  HABITADA_POR_PROPIETARIO = 'HABITADA_POR_PROPIETARIO',
  HABITADA_POR_ARRENDATARIO = 'HABITADA_POR_ARRENDATARIO',
  DESHABITADA_TEMPORALMENTE = 'DESHABITADA_TEMPORALMENTE',
  DESHABITADA_PERMANENTE = 'DESHABITADA_PERMANENTE',
  EN_VENTA_POR_PROPIETARIO = 'EN_VENTA_POR_PROPIETARIO',
  EN_ARRIENDO_POR_PROPIETARIO = 'EN_ARRIENDO_POR_PROPIETARIO',
  DISPONIBLE_PARA_VENTA_LOTEO = 'DISPONIBLE_PARA_VENTA_LOTEO',
  EN_CONSTRUCCION = 'EN_CONSTRUCCION',
  SIN_CONSTRUCCION = 'SIN_CONSTRUCCION',
  OTRO = 'OTRO',
}
