export enum RolEnComiteEnum {
  PRESIDENTE = 'PRESIDENTE',
  SECRETARIO = 'SECRETARIO',
  TESORERO = 'TESORERO',
  DIRECTOR = 'DIRECTOR',
  MIEMBRO_TITULAR = 'MIEMBRO_TITULAR',
  MIEMBRO_SUPLENTE = 'MIEMBRO_SUPLENTE',
  ASESOR = 'ASESOR',
  OTRO = 'OTRO',
}
