export enum RolEnLoteoEnum {
  ADMINISTRADOR_LOTEO_PRINCIPAL = 'ADMINISTRADOR_LOTEO_PRINCIPAL',
  ADMINISTRADOR_LOTEO_SECUNDARIO = 'ADMINISTRADOR_LOTEO_SECUNDARIO',
  PROPIETARIO_PRINCIPAL_RESIDENTE = 'PROPIETARIO_PRINCIPAL_RESIDENTE',
  PROPIETARIO_PRINCIPAL_NO_RESIDENTE = 'PROPIETARIO_PRINCIPAL_NO_RESIDENTE',
  PROPIETARIO_SECUNDARIO = 'PROPIETARIO_SECUNDARIO',
  ARRENDATARIO = 'ARRENDATARIO',
  RESIDENTE_AUTORIZADO_FAMILIAR = 'RESIDENTE_AUTORIZADO_FAMILIAR',
  PERSONAL_SERVICIO_LOTEO = 'PERSONAL_SERVICIO_LOTEO',
  INVITADO_PERMANENTE = 'INVITADO_PERMANENTE',
  OTRO = 'OTRO',
}
